### ISSUE TITLE
Connection failed reason for W3CWebSocket

### ISSUE THREAD

**Issue by yaddran** [theturtle32/WebSocket-Node#272]
For one of our Phoenix projects I have stumbled upon a need to know the reason why the connection was not successful. I am passing
```javascript
transport: require('websocket').w3cwebsocket
```
to the Phoenix Socket. Everything is working fine but in Phoenix we can refuse the connection. In that case the server would send 403. In other case, for instance no network, the connection would also fail. I needed to know the reason for the failed connection. However, the W3CWebSocket is handling the error and hiding the passed error object, here:
```javascript
this._client.on('connectFailed', function() {
        onConnectFailed.call(self);
});
```
So, I suggest we pass the error object further, like this:
```javascript
this._client.on('connectFailed', function(error) {
        onConnectFailed.call(self, error);
});
```
and then in onConnectFailed pass the error object in the event, like this this:
```javascript
function onConnectFailed(error) {
    destroy.call(this);
    this._readyState = CLOSED;

    try {
        var event = new yaeti.Event('error');
        event.data = error;
        this.dispatchEvent(event);
    } finally {
        this.dispatchEvent(createCloseEvent(1006, 'connection failed'));
    }
}
```
In this way we would at least have a notion why the connection failed. I guess that passing the response.statusCode, as well, from WebSocketClient for this case would be a bit too much to ask?

**Comment by theturtle32** [comment]
As handy as it might be to have access to more insight as to why the connection failed here, the purpose of the W3CWebSocket implementation is to exactly implement the browser WebSocket API as defined by the W3C, so that the same client code can be used both on the client and on the server if needed.

The specification does not allow for exposing this level of detail. Browsers do not, and so we should not either.

https://www.w3.org/TR/2011/WD-websockets-20110929/
