### ISSUE TITLE
Feature request: allow use of status codes 1012, 1013

### ISSUE THREAD

**Issue by braytak** [theturtle32/WebSocket-Node#292]
The following are IANA registered status code extensions (https://www.iana.org/assignments/websocket/websocket.xml):

- 1012-Service Restart
- 1013-Try Again Later (originally labelled Service Overload)

Use cases for these are described  in the reference document associated with the codes (see the IANA assignments document above).

Beats overloading a normative code...

**Comment by ibc** [comment]
What does "Service Restart" mean? That's obviously related to a specific application/usage. `WebSocket-Node` is a library (not an application) so it has no way to know whether the sockets have been closed due to "service restart" or due to any other reason.

Anyhow, the library already allows passing specific status codes when calling `close()` on the WS connections. It's up to the application whether to set a specific status code or not.

**Comment by theturtle32** [comment]
@ibc - This is actually a legitimate request. Check out the link provided.

**Comment by theturtle32** [comment]
Fixed in 0713ded3214231d34ca9b6f94fe8483e70b6a1e9

**Comment by ibc** [comment]
Sorry, I thought that the issue was about making WebSocket-Node automatically generating those status codes. I was not aware that some 1XXX were not allowed by the library API.
